cache:
  - vendor/bundle -> .appveyor.yml

environment:
  matrix:
    - RUBY_VERSION: 23-x64
      IMAGEMAGICK_VERSION: 6.8.9
      PATCH_VERSION: 10
    - RUBY_VERSION: 23-x64
      IMAGEMAGICK_VERSION: 6.9.10
      PATCH_VERSION: 40
    - RUBY_VERSION: 24-x64
      IMAGEMAGICK_VERSION: 6.8.9
      PATCH_VERSION: 10
    - RUBY_VERSION: 24-x64
      IMAGEMAGICK_VERSION: 6.9.10
      PATCH_VERSION: 40
    - RUBY_VERSION: 25-x64
      IMAGEMAGICK_VERSION: 6.8.9
      PATCH_VERSION: 10
    - RUBY_VERSION: 25-x64
      IMAGEMAGICK_VERSION: 6.9.10
      PATCH_VERSION: 40
    - RUBY_VERSION: 26-x64
      IMAGEMAGICK_VERSION: 6.8.9
      PATCH_VERSION: 10
    - RUBY_VERSION: 26-x64
      IMAGEMAGICK_VERSION: 6.9.10
      PATCH_VERSION: 40

install:
  - appveyor-retry appveyor DownloadFile https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/ImageMagick-%IMAGEMAGICK_VERSION%-%PATCH_VERSION%-Q16-x64-dll.exe
  - ImageMagick-%IMAGEMAGICK_VERSION%-%PATCH_VERSION%-Q16-x64-dll.exe /VERYSILENT /TASKS=install_Devel
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Program Files\ImageMagick-%IMAGEMAGICK_VERSION%-Q16;%PATH%
  - bundle install --path=vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake -rdevkit
