language: ruby
os:
  - linux
  - osx
env:
  # Currently successful release
  - IMAGEMAGICK_VERSION=6.6.9-10
  # Ubuntu's current stable release
  - IMAGEMAGICK_VERSION=6.7.7-10
  # Latest 6.7 release
  - IMAGEMAGICK_VERSION=6.7.9-10
  # Latest 6.8 release
  - IMAGEMAGICK_VERSION=6.8.9-6
  # Try with HDRI support, we don't mind if this fails currently.
  - IMAGEMAGICK_VERSION=6.8.9-6 CONFIGURE_OPTIONS=--enable-hdri
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
  - dpkg --list imagemagick
  - sudo apt-get remove imagemagick
  - sudo apt-get install build-essential libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
  - sudo apt-get build-dep imagemagick
  - wget http://www.imagemagick.org/download/releases/ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
  - tar -xzvf ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
  - cd ImageMagick-${IMAGEMAGICK_VERSION}
  - ./configure --prefix=/usr $CONFIGURE_OPTIONS
  - sudo make install
  - cd ..
  - sudo ldconfig
  - else
  - brew update
  - brew install imagemagick
  - fi
rvm:
  - 1.9
  - 2.0
  - 2.1
matrix:
  exclude:
#    - rvm: 1.9
#      env: IMAGEMAGICK_VERSION=6.7.7-10
    - rvm: 1.9
      env: IMAGEMAGICK_VERSION=6.7.9-10
#    - rvm: 1.9
#      env: IMAGEMAGICK_VERSION=6.8.9-6
    - rvm: 1.9
      env: IMAGEMAGICK_VERSION=6.8.9-6 CONFIGURE_OPTIONS=--enable-hdri
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.7.7-10
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.7.9-10
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.8.9-6
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.8.9-6 CONFIGURE_OPTIONS=--enable-hdri
  allow_failures:
    - env: IMAGEMAGICK_VERSION=6.7.7-10
    - env: IMAGEMAGICK_VERSION=6.7.9-10
    #- env: IMAGEMAGICK_VERSION=6.8.9-6
    - env: IMAGEMAGICK_VERSION=6.8.9-6 CONFIGURE_OPTIONS=--enable-hdri
