language: ruby

cache:
  directories:
    - ~/.cache/rubocop_cache
    - vendor/bundle
    - build-ImageMagick

dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - libx11-dev
      - libxext-dev
      - zlib1g-dev
      - liblcms2-dev
      - libpng-dev
      - libjpeg-dev
      - libfreetype6-dev
      - libxml2-dev
      - libtiff5-dev
      - libwebp-dev
      - ghostscript
      - ccache

os:
  - linux

sudo: required

env:
  - IMAGEMAGICK_VERSION=6.7.7-10

before_install:
  - /bin/bash before_install_$TRAVIS_OS_NAME.sh

install: bundle install --path=vendor/bundle --verbose

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
