language: ruby

cache:
  directories:
    - ~/.ccache

os:
  - linux

sudo: required

env:
  - IMAGEMAGICK_VERSION=7.0.8-34
  - IMAGEMAGICK_VERSION=7.0.8-34 CONFIGURE_OPTIONS=--enable-hdri

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh

install: bundle install --verbose

script: rake test # TODO: now, run `rake test` which is a part of `rake`. need to fix `rake spec`

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  include:
    - rvm: 2.3
      env: STYLE_CHECKS=true IMAGEMAGICK_VERSION=7.0.8-34

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a98c1112f5d60f97a532
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
